<?php

namespace Drupal\queue_sync\Form;

use Drupal\Core\Form\FormBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

class GenerateDummyForm extends FormBase {
  public function getFormId() {
    return 'queue_sync_generate_dummy_form';
  }

  public function buildForm(array $form, FormStateInterface $form_state) {
    $config = \Drupal::config('queue_sync.settings');
    $current_time = \Drupal::time()->getCurrentTime();
    $formatter = \Drupal::service('date.formatter');
    
    // Show current time
    $form['current_time'] = [
      '#type' => 'markup',
      '#markup' => '<div class="current-time-info">' .
        '<strong>' . $this->t('Current Time:') . '</strong> ' .
        $formatter->format($current_time, 'custom', 'Y-m-d H:i:s') .
        '</div>',
    ];
    
    $form['items'] = [
      '#type' => 'number',
      '#title' => $this->t('Number of dummy items'),
      '#description' => $this->t('Total number of items to create in this batch.'),
      '#default_value' => 5,
      '#min' => 1,
      '#max' => 1000,
      '#required' => TRUE,
    ];
    
    $default_delay = $config->get('default_delay_minutes') ?? 1;
    $default_delay_seconds = $default_delay * 60;
    
    $form['delay_minutes'] = [
      '#type' => 'number',
      '#title' => $this->t('Delay (minutes) before processing'),
      '#description' => $this->t('Number of minutes to wait before this batch starts processing. Current default: @default', ['@default' => $this->formatMinutes($default_delay)]),
      '#default_value' => $default_delay,
      '#min' => 0,
      '#step' => 0.5,
      '#required' => TRUE,
      '#field_suffix' => $this->t('minutes'),
      '#attributes' => ['class' => ['delay-minutes']],
      '#suffix' => '<div class="delay-minutes-info">' .
        '<small><strong>' . $this->t('Info:') . '</strong> ' .
        '<span id="delay-minutes-display">' . $this->formatMinutes($default_delay) . '</span>' .
        '</small></div>' .
        '<div class="batch-preview">' . 
        '<strong>' . $this->t('Batch will run at:') . '</strong> ' .
        '<span id="run-time-preview">' . $formatter->format($current_time + $default_delay_seconds, 'custom', 'Y-m-d H:i:s') . '</span>' .
        '</div>',
    ];
    
    $form['submit'] = [
      '#type' => 'submit',
      '#value' => $this->t('Generate Batch'),
    ];
    
    $form['#attached']['library'][] = 'queue_sync/settings';
    
    // Add JavaScript to update preview
    $form['#attached']['drupalSettings']['queueSync'] = [
      'currentTime' => $current_time,
    ];
    
    return $form;
  }

  public function submitForm(array &$form, FormStateInterface $form_state) {
    $items = (int) $form_state->getValue('items');
    $delay = (int) $form_state->getValue('delay_minutes');
    $run_at = time() + ($delay * 60);
    $data = [];
    for ($i = 1; $i <= $items; $i++) {
      $data[] = [
        'title' => 'Dummy item ' . $i . ' at ' . date('Y-m-d H:i:s'),
        'body' => 'Generated by queue_sync.',
      ];
    }
    // Create batch via service.
    \Drupal::service('queue_sync.runner')->createBatch($data, $run_at);
    $this->messenger()->addMessage($this->t('Dummy batch created with @count items.', ['@count' => $items]));
    $form_state->setRedirectUrl(Url::fromRoute('queue_sync.admin'));
  }
  
  /**
   * Format minutes value for display in info.
   */
  protected function formatMinutes($minutes) {
    if ($minutes == 0.5) {
      return $this->t('half minute (30 seconds)');
    }
    if ($minutes == 1) {
      return $this->t('1 minute');
    }
    if ($minutes < 1) {
      $seconds = $minutes * 60;
      return $this->t('@minutes minutes (@seconds seconds)', [
        '@minutes' => $minutes,
        '@seconds' => $seconds,
      ]);
    }
    if (floor($minutes) == $minutes) {
      return $this->t('@minutes minutes', ['@minutes' => $minutes]);
    }
    $seconds = round(($minutes - floor($minutes)) * 60);
    $whole_minutes = floor($minutes);
    if ($seconds == 30) {
      return $this->t('@minutes and a half minutes', ['@minutes' => $whole_minutes]);
    }
    return $this->t('@minutes minutes (@seconds seconds)', [
      '@minutes' => $whole_minutes,
      '@seconds' => $seconds,
    ]);
  }
}
